title: default-project-template
hero_image: images/banner.png
description: default-project-template description
version: 1
listed: false
copyedit: false
last_tested: "2025-01-01"
steps:
  - title: Add a sprite
    completion:
      - engaged      
  - title: Animate
  - title: Record and play sound
  - title: Export it
    completion:
      - internal
      - external
  - title: Mentor instructions